#!/usr/bin/env sh

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="Iosevka Nerd Font Mono" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
# SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

PADDINGS=3 # All paddings use this value (icon, label, background)

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

SHADOW=on

# Setting up the general bar appearance and default values
sketchybar --bar     height=50                                         \
                     color=$BAR_COLOR                                  \
                     shadow=$SHADOW                                    \
                     position=right                                     \
                     sticky=on                                         \
                     padding_right=5                                  \
                     padding_left=5                                   \
                     corner_radius=9                                   \
                     y_offset=10                                       \
                     margin=3                                         \
                     blur_radius=20                                    \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Bold:14.0"                       \
                     icon.color=$ICON_COLOR                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$FONT:Semibold:13.0"                  \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     background.padding_right=$PADDINGS                \
                     background.padding_left=$PADDINGS                 \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=11                 \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=$SHADOW

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"

# Center
# source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/calendar.sh"

############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
